# Generated by Django 4.2.5 on 2024-04-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='cust',
            name='user_permissions',
            field=models.ManyToManyField(related_name='cust_users', to='auth.permission'),
        ),
    ]
