# Generated by Django 4.2.5 on 2024-04-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Store', '0002_remove_cust_user_permissions_cust_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust',
            name='groups',
        ),
        migrations.AddField(
            model_name='cust',
            name='groups',
            field=models.ManyToManyField(related_name='custom_users', to='auth.group'),
        ),
    ]
