# Generated by Django 4.2.5 on 2024-04-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_remove_cust_cust_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'store_cust_groups',
                'managed': False,
            },
        ),
    ]
