# Generated by Django 4.2.5 on 2024-04-08 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_custgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.cust')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.item')),
            ],
        ),
    ]
