# Generated by Django 4.2.5 on 2024-04-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_itemrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='good item with good price you can order it any time from our store have amazing ablities', max_length=500),
        ),
    ]
