# Generated by Django 4.2.5 on 2024-04-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discAv',
            field=models.BooleanField(default=True),
        ),
    ]
