# Generated by Django 4.2.5 on 2024-04-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_remove_order_month_remove_order_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bi_st',
        ),
    ]
