# Generated by Django 4.2.5 on 2024-04-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_remove_order_bi_st'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_percentage',
        ),
    ]
