# Generated by Django 4.2.5 on 2024-04-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_remove_order_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='randomItem.jpg', upload_to='item_images/'),
        ),
    ]
