# Generated by Django 4.2.5 on 2024-04-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_remove_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='static/randomItem.jpg', upload_to='item_images/'),
        ),
    ]
