# Generated by Django 4.2.5 on 2024-04-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
