# Generated by Django 4.2.5 on 2024-04-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(default='good category with good prices you can order it any time from our store have amazing ablities', max_length=500)),
            ],
        ),
    ]
