# Generated by Django 4.2.5 on 2024-04-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0024_remove_item_category_item_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='Others', max_length=100),
        ),
    ]
