# Generated by Django 4.2.5 on 2024-04-15 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0025_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
