# Generated by Django 4.2.5 on 2024-04-16 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0029_remove_coupon_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coupon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.coupon')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.cust')),
            ],
        ),
    ]
