# Generated by Django 4.2.5 on 2024-05-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalDash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='full_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
