# Generated by Django 4.2.5 on 2024-05-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generalDash', '0002_guest_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='sess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('gues', models.ForeignKey(default='Others', on_delete=django.db.models.deletion.CASCADE, to='generalDash.guest')),
            ],
        ),
    ]
