# Generated by Django 4.2.5 on 2024-05-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalDash', '0003_sess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
