# Generated by Django 4.2.5 on 2024-05-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalDash', '0004_alter_guest_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='guestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'store_cust_groups',
                'managed': False,
            },
        ),
    ]
