# Generated by Django 4.2.5 on 2024-05-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalDash', '0005_guestgroup'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guestgroup',
            table='generalDash_guest_groups',
        ),
    ]
