# Generated by Django 4.2.5 on 2024-05-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalDash', '0006_alter_guestgroup_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sess',
        ),
    ]
