# Generated by Django 4.2.5 on 2024-05-07 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalDash', '0008_sess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sess',
        ),
    ]
